// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>
#define Int int32_t

using namespace Rcpp;

// computeKernelCpp
NumericMatrix CalculateKernelCpp(List graph_info_list, NumericVector par_r, Int kernel_type);
RcppExport SEXP graphkernels_CalculateKernelCpp(SEXP graph_info_listSEXP, SEXP par_rSEXP, SEXP kernel_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type graph_info_list(graph_info_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par_r(par_rSEXP);
    Rcpp::traits::input_parameter< Int >::type kernel_type(kernel_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(CalculateKernelCpp(graph_info_list, par_r, kernel_type));
    return rcpp_result_gen;
END_RCPP
}
